const express = require("express");
const AdminJS = require("adminjs");
const AdminJSExpress = require("@adminjs/express");
const AdminJSSequelize = require("@adminjs/sequelize");
AdminJS.registerAdapter(AdminJSSequelize);
const adminJS = require("./admin/index");
const PORT = 3000;
const app = express();
const router = AdminJSExpress.buildRouter(adminJS);
app.use(adminJS.options.rootPath, router);
app.listen(PORT, () => console.log(`Admin JS is running on port: ${PORT}`));
