const AdminJS = require("adminjs");
const {
  AboutUs,
  AIMLAutomation,
  BigData,
  Blog,
  BlogCategories,
  Careers,
  CaseStudies,
  Client,
  CompanyInfo,
  ContactUs,
  HomePage,
  Industry,
  OpenJobPositions,
  ProductDevelopment,
  Recognition,
  TeamMembers,
  Technologies,
  Testimonials,
} = require("../models");
const adminJS = new AdminJS({
  rootPath: "/admin",
  resources: [
    AboutUs,
    AIMLAutomation,
    BigData,
    Blog,
    BlogCategories,
    Careers,
    CaseStudies,
    Client,
    CompanyInfo,
    ContactUs,
    HomePage,
    Industry,
    OpenJobPositions,
    ProductDevelopment,
    Recognition,
    TeamMembers,
    Technologies,
    Testimonials,
  ],
  branding: {
    companyName: "Oneture",
    softwareBrothers: "false",
  },
});
module.exports = adminJS;
